const { withAppBuildGradle } = require('expo/config-plugins');

/**
 * 为 Android release 构建注入正式签名配置。
 *
 * 背景：`expo prebuild` 生成的 `android/app/build.gradle` 默认让 release 也使用
 * debug 证书签名（模板行为），且 prebuild 每次都会清空重建 `android/`，
 * 因此不能直接手改 build.gradle —— 必须通过 config plugin 注入。
 *
 * 做法：在 build.gradle 末尾追加第二个 `android { }` 块（Groovy 允许重复配置，
 * 后配置覆盖先配置）。凭据从全局 `~/.gradle/gradle.properties` 读取，
 * 由 `scripts/create-release-keystore.sh` 写入：
 *
 *   CALENDAR_UPLOAD_STORE_FILE
 *   CALENDAR_UPLOAD_STORE_PASSWORD
 *   CALENDAR_UPLOAD_KEY_ALIAS
 *   CALENDAR_UPLOAD_KEY_PASSWORD
 *
 * 若这些属性不存在（例如他人的机器），则保持模板默认的 debug 签名，
 * 保证 `assembleDebug` / 他人构建不受影响；构建 release 时会打印警告。
 *
 * 注意：这里用 `expo/config-plugins` 而非 `@expo/config-plugins` —— 前者由
 * 直接依赖 `expo` 保证可解析，无需额外安装包。
 */

const MARKER = '// @generated by plugins/withAndroidReleaseSigning';

const SIGNING_SNIPPET = `
${MARKER} — 请勿手改，prebuild 会重新生成
// release 正式签名：凭据见 ~/.gradle/gradle.properties
android {
    signingConfigs {
        release {
            if (project.hasProperty('CALENDAR_UPLOAD_STORE_FILE')) {
                storeFile file(CALENDAR_UPLOAD_STORE_FILE)
                storePassword CALENDAR_UPLOAD_STORE_PASSWORD
                keyAlias CALENDAR_UPLOAD_KEY_ALIAS
                keyPassword CALENDAR_UPLOAD_KEY_PASSWORD
            }
        }
    }
    buildTypes {
        release {
            if (project.hasProperty('CALENDAR_UPLOAD_STORE_FILE')) {
                signingConfig signingConfigs.release
            }
        }
    }
}

gradle.taskGraph.whenReady { graph ->
    def buildingRelease = graph.allTasks.any { t -> t.name.toLowerCase().contains('release') }
    if (buildingRelease && !project.hasProperty('CALENDAR_UPLOAD_STORE_FILE')) {
        logger.warn('[signing] CALENDAR_UPLOAD_STORE_FILE 未配置，release 包将使用 debug 证书签名，无法上架应用商店。')
    }
}
`;

module.exports = function withAndroidReleaseSigning(config) {
  return withAppBuildGradle(config, (cfg) => {
    if (cfg.modResults.language !== 'groovy') {
      throw new Error(
        '[withAndroidReleaseSigning] 仅支持 Groovy 版 build.gradle，当前为: ' +
          cfg.modResults.language
      );
    }
    // prebuild 会重新生成 build.gradle，但同一轮 mod 可能执行多次，这里做幂等保护
    if (!cfg.modResults.contents.includes(MARKER)) {
      cfg.modResults.contents += SIGNING_SNIPPET;
    }
    return cfg;
  });
};
